server:
  port: 14001

spring:
  application:
    name: mall-cart
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 192.168.31.70:8888
  redis:
    host: 192.168.31.70
    port: 6379
  session:
    store-type: redis
  servlet:
    session:
      timeout: 30m
  thymeleaf:
    cache: false
  # 服务追踪
  zipkin:
    # zipkin服务的地址
    base-url: http://192.168.31.70:9411/
    # 关闭服务发现，否则Spring Cloud会把zipkin的url当做服务名称
    discovery-client-enabled: false
    sender:
      type: web # 设置使用http的方式传输数据
  sleuth:
    sampler:
      probability: 1 # 设置抽样采集率为100%，默认为0.1，即10%

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true

# 线程池参数配置
grain:
  mall:
    thread:
      core-size: 20
      max-size: 200
      keep-alive-time: 10