spring:
  application:
    name: mall-seckill
  thymeleaf:
    cache: false
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 192.168.31.70:8888
        port: 8719
  redis:
    host: 192.168.31.70
    port: 6379
  session:
    store-type: redis
  rabbitmq:
    host: 192.168.31.70
    port: 5672
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true

server:
  port: 15001
