spring:
  application:
    name: mall-seckill

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.31.70
    port: 6379
  session:
    store-type: redis
server:
  port: 15001
