spring:
  application:
    name: mall-seckill

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.31.70
    port: 6379
  session:
    store-type: redis
  rabbitmq:
    host: 192.168.31.70
    port: 5672
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true

server:
  port: 15001
